### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by abbshr** [abbshr/Kedi#1]
# v0.1.0
- [x] 配置 DSL
- [x] Pipeline DSL
- [x] 实现简单的 yaml 格式语法的编译器
- [x] `select` / `fulfill` 语句先支持内部 DSL
- [x] 配置项
- [x] 构建完善的内部基础设施
- [x] 确定各个组件的 API
- [x] 确定启动流程
- [ ] 确定调度机制和通信机制

# v0.2.0
- [ ] 实现 metrics 与细致的监控链路
- [ ] 实现 rest services

# v1.0.0
- [ ] 实现更多的 `calcs`
- [ ] 安全机制
- [ ] 为 `select` / `fulfill` 语句的 yaml 格式查询语法构建编译器
- [ ] DAG Container 的扩展（分布式 Pipeline）
- [ ] rest 能输出 json 描述的 DAG
